apiVersion: policy.antaeus.io/v0alpha1
kind: Policy
metadata:
  name: &policy-name alias-name
  description: *policy-name
spec:
  defaultOutcome: review
  rules:
    - id: check
      when: The condition applies.
      outcome: review
